# Generated by Django 5.0.2 on 2025-09-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staffprofile",
            name="assigned_grades",
        ),
        migrations.RemoveField(
            model_name="staffprofile",
            name="assigned_subjects",
        ),
        migrations.RemoveField(
            model_name="staffprofile",
            name="teaching_experience",
        ),
        migrations.AddField(
            model_name="staff",
            name="assigned_grades",
            field=models.JSONField(
                default=list, help_text="Grade levels assigned to this staff member"
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="assigned_subjects",
            field=models.JSONField(
                default=list, help_text="Subjects assigned to this staff member"
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="teaching_experience",
            field=models.PositiveIntegerField(
                default=0, help_text="Years of teaching experience"
            ),
        ),
    ]
